sudo: required
language: c

env:
  - PGVERSION=9.5
  - PGVERSION=9.6

before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - sudo sh ./apt.postgresql.org.sh

install:
  - packages="postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-common"
  - sudo service postgresql stop
  - echo 'exit 0' | sudo tee /etc/init.d/postgresql
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $packages

before_script:
  - sudo /etc/init.d/postgresql restart
  - sudo chmod a+x /etc/init.d/postgresql
  - sudo pg_createcluster --start $PGVERSION feedback -p 55435 -- -A trust
  - sudo make install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config

script:
  - psql -c 'CREATE EXTENSION pg_feedback;' -p 55435 -U postgres
  - psql -c 'SELECT feedback();' -p 55435 -U postgres --tuples-only --no-align | python -m json.tool
